version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - mynetwork

  producer:
    build:
      context: .
      dockerfile: DockerfileProducer
    depends_on:
      - kafka
    env_file:
      - .env
    networks:
      - mynetwork
    

  consumer:
    build:
      context: .
      dockerfile: DockerfileConsumer
    depends_on:
      - kafka
      - flask-server
    env_file:
      - .env
    networks:
      - mynetwork
    

  flask-server:
    build:
      context: .
      dockerfile: DockerfileFlask
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    env_file:
      - .env
     
    networks:
      - mynetwork
      
  

    
      

networks:
  mynetwork:

